// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://harfpzgkgpnlpwfdcbdv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhhcmZwemdrZ3BubHB3ZmRjYmR2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5MDMyODksImV4cCI6MjA2NTQ3OTI4OX0.z2nV-97ir0TaKS_yLk2CRdwV1z1XbOWEyO6Nlbwtw9k";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);